apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress-config.fullname" . }}-hello-world-ingress
  labels:
  {{- include "ingress-config.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hello-world-httpd
            port:
              number: 80
        path: /(.*)
        pathType: Prefix