apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fluentbitdaemon.fullname" . }}-fluent-bit
  labels:
    k8s-app: fluent-bit-logging
    kubernetes.io/cluster-service: "true"
    version: v1
  {{- include "fluentbitdaemon.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
      version: v1
    {{- include "fluentbitdaemon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        kubernetes.io/cluster-service: "true"
        version: v1
      {{- include "fluentbitdaemon.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.fluentBit.fluentBit.image.repository }}:{{ .Values.fluentBit.fluentBit.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.fluentBit.fluentBit.imagePullPolicy }}
        name: fluent-bit
        resources: {}
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /fluent-bit/etc/
          name: fluent-bit-config
      serviceAccountName: {{ include "fluentbitdaemon.fullname" . }}-fluent-bit
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
      - configMap:
          name: fluent-bit-config
        name: fluent-bit-config